allowBuilds:
  unrs-resolver: false
minimumReleaseAgeExclude:
  - prettier@3.9.0

overrides:
  lightningcss: "1.30.1"
  react-native-css>lightningcss: "1.30.1"
  tailwindcss>lightningcss: "1.30.1"
  "@tailwindcss/postcss>lightningcss": "1.30.1"